# Regras

Entendendo o desafio:

Precisarei de 3 arquivos:

1.   train.csv
2.   test.csv
3.   sample_submission.csv

Precisarei tratar ambos


1.   Nulos
2.   Duplicados
3.   Maiusculos e Minusculos

Conjuntos e Tipos:


1.   train.csv - o conjunto de treinamento
2.   test.csv - o conjunto de testes
1.   sample_submission.csv - um arquivo de envio de amostra no formato correto

Colunas:
*   id- um identificador único para cada tweet
*   text - o texto do tweet
*   location - o local de onde o tweet foi enviado (pode estar em branco)
*   keyword - uma palavra-chave específica do tweet (pode estar em branco)
*target- somente em train.csv , isso denota se um tweet é sobre um desastre real ( 1) ou não ( 0)

primeiro, transformar os dados dos tweets em dado numéricos que uma IA possa utilizar como entrada.

bibliotecas do python:
*   NLTK
*   Spacy

estruturar um modelo de inteligência artificial para ser treinado utilizando os textos transformados em entradas, e as classificações em saída.


Última dica: Tente usar bibliotecas estabelecidas, como o Keras, TensorFlow, PyTorch ou mesmo a biblioteca de Transformers do Hugging Face!

# Leitura

In [ ]:
import zipfile
import os
import pandas as pd

caminho_zip = "/content/nlp-getting-started.zip"
pasta_destino = "/content/arquivo"


with zipfile.ZipFile(caminho_zip, "r") as zip_referencia:
  zip_referencia.extractall(pasta_destino)

  print(f"Arquivos dentro do zip: {zip_referencia.namelist()}")
  print(f"Arquivo extraidos: {pasta_destino}")

Arquivos dentro do zip: ['sample_submission.csv', 'test.csv', 'train.csv']
Arquivo extraidos: /content/arquivo

In [ ]:
df_submission = pd.read_csv("/content/arquivo/sample_submission.csv")
print(df_submission.info())
print(df_submission.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3263 non-null   int64
 1   target  3263 non-null   int64
dtypes: int64(2)
memory usage: 51.1 KB
None
   id  target
0   0       0
1   2       0
2   3       0
3   9       0
4  11       0

In [ ]:
df_test = pd.read_csv("/content/arquivo/test.csv")
print(df_test.info())
print(df_test.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        3263 non-null   int64
 1   keyword   3237 non-null   object
 2   location  2158 non-null   object
 3   text      3263 non-null   object
dtypes: int64(1), object(3)
memory usage: 102.1+ KB
None
   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
df_train = pd.read_csv("/content/arquivo/train.csv")
print(df_train.info())
print(df_train.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB
None
   id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...

   target
0       1
1       1
2       1
3       1
4       1

# Visualização nulos

In [19]:
df_submission.isnull().sum()

id        0
target    0
dtype: int64

In [23]:
df_test.isnull().sum()

id          0
keyword     0
location    0
text        0
dtype: int64

In [21]:
df_train.isnull().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

# Tratamento Nulos

In [22]:
df_test["location"].fillna("desconhecido", inplace=True)
df_test["keyword"].fillna("desconhecido", inplace=True)

<ipython-input-22-43aa6ab20b33>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test["location"].fillna("desconhecido", inplace=True)
<ipython-input-22-43aa6ab20b33>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test["keyword"].fillna("desconhecido", inplace=True)

In [24]:
df_train["keyword"].fillna("desconhecido", inplace=True)
df_train["location"].fillna("desconhecido", inplace=True)

<ipython-input-24-62ceba184ca2>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train["keyword"].fillna("desconhecido", inplace=True)
<ipython-input-24-62ceba184ca2>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train["location"].fillna("desconhecido", inplace=True)

# Tratando Duplicados

In [14]:
df_submission.drop_duplicates(inplace=True)
df_test.drop_duplicates(inplace=True)
df_train.drop_duplicates(inplace=True)

# Normalização de caracteres

In [30]:
df_submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3263 non-null   int64
 1   target  3263 non-null   int64
dtypes: int64(2)
memory usage: 51.1 KB

In [31]:
df_test.info()
#1   keyword   3263 non-null   object
#2   location  3263 non-null   object
#3   text      3263 non-null   object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        3263 non-null   int64
 1   keyword   3263 non-null   object
 2   location  3263 non-null   object
 3   text      3263 non-null   object
dtypes: int64(1), object(3)
memory usage: 102.1+ KB

In [33]:
df_train.info()
# 1   keyword   7613 non-null   object
# 2   location  7613 non-null   object
# 3   text      7613 non-null   object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7613 non-null   object
 2   location  7613 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

Tranformando objetos em string para normalizar - acentos, espaços, numeros, maiusculas e minusculas

In [35]:
!pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 10.0 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0

In [39]:
from unidecode import unidecode

dataframes_tratamento = [df_train, df_test]

for df in dataframes_tratamento:
  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.lower()
    df[col] = df[col].apply(unidecode)
    df[col] = df[col].str.strip()
    df[col] = df[col].str.replace(r"[^\w\s]", "", regex=True)

In [40]:
df_test.info()
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        3263 non-null   int64
 1   keyword   3263 non-null   object
 2   location  3263 non-null   object
 3   text      3263 non-null   object
dtypes: int64(1), object(3)
memory usage: 102.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7613 non-null   object
 2   location  7613 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

# Tokenização

Download dos Stopwords da lingua portuguesa-Remoção de Stopwords

In [62]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stopwords_en = set(stopwords.words('english'))
df_train['tokens'] = df_train['text'].apply(lambda x: str(x).lower().split())
df_test['tokens'] = df_test['text'].apply(lambda x: str(x).lower().split())

df_train['tokens_sem_stopwords'] = df_train['tokens'].apply(
    lambda tokens: [palavra for palavra in tokens if palavra not in stopwords_en]
)
df_test['tokens_sem_stopwords'] = df_test['tokens'].apply(
    lambda tokens: [palavra for palavra in tokens if palavra not in stopwords_en]
)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Exemplo de como a tokenização funcionou

In [63]:
df_train[['text', 'tokens', 'tokens_sem_stopwords']].sample(5)

,text,tokens,tokens_sem_stopwords
2216,best windows torrent client was recommended de...,"[best, windows, torrent, client, was, recommen...","[best, windows, torrent, client, recommended, ..."
1023,aint no bags in the trunk its a body,"[aint, no, bags, in, the, trunk, its, a, body]","[aint, bags, trunk, body]"
5424,you can stop panicking ogtomd httpstcozvre6f...,"[you, can, stop, panicking, ogtomd, httpstcozv...","[stop, panicking, ogtomd, httpstcozvre6ffnyd]"
891,a nightmare on elm street is getting remade ag...,"[a, nightmare, on, elm, street, is, getting, r...","[nightmare, elm, street, getting, remade, http..."
6278,johngreen storm and silence by robthier_en,"[johngreen, storm, and, silence, by, robthier_en]","[johngreen, storm, silence, robthier_en]"

# Vetorização

Usaremos o IDF - Raridade de palavras em outros Tweets - Frequencias Unicas

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [65]:
# Junta os tokens em strings novamente
df_train['texto_final'] = df_train['tokens_sem_stopwords'].apply(lambda x: ' '.join(x))
df_test['texto_final'] = df_test['tokens_sem_stopwords'].apply(lambda x: ' '.join(x))

In [66]:
# Cria o vetor de TF-IDF
vetorizador = TfidfVectorizer()

# Ajusta e transforma os textos de treino
X_train_tfidf = vetorizador.fit_transform(df_train['texto_final'])

# Apenas transforma o teste (sem ajustar de novo!)
X_test_tfidf = vetorizador.transform(df_test['texto_final'])

# Modelo de Regressão

In [68]:
# Importa a biblioteca do modelo
from sklearn.linear_model import LogisticRegression

# Define os dados de entrada e saída
X = X_train_tfidf
y = df_train['target']

# Cria o modelo
modelo = LogisticRegression(max_iter=1000)

# Treina (ajusta) o modelo com os dados
modelo.fit(X, y)

LogisticRegression(max_iter=1000)

In [71]:
from sklearn.metrics import classification_report, accuracy_score

# Faz previsões com os dados de treino
y_pred = modelo.predict(X)

# Avalia o desempenho
print("Acurácia:", accuracy_score(y, y_pred))
print(classification_report(y, y_pred))

Acurácia: 0.8930776303691055
              precision    recall  f1-score   support

           0       0.86      0.97      0.91      4342
           1       0.96      0.79      0.86      3271

    accuracy                           0.89      7613
   macro avg       0.91      0.88      0.89      7613
weighted avg       0.90      0.89      0.89      7613

In [70]:
# Aplica o modelo treinado no dataset de teste
y_test_pred = modelo.predict(X_test_tfidf)

# Adiciona as previsões no df_test
df_test['target_pred'] = y_test_pred

# Visualiza alguns resultados
df_test[['text', 'target_pred']].sample(5)

                                                   text  target_pred
2680  the sun is shining on this house now but imagi...            1
1378  be safe and be prepare from emergency kits to ...            1
890   allen west obama is a clear and present danger...            0
1687  im so dried out in this desert let me know i w...            0
2423  worker rescued from top of central street wate...            1