In [2]:
import pandas as pd
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'#o padrão do sheets é 0, primeira pagina é emissoes_co2
dados_emissões = pd.read_excel(url)
dados_emissões.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [6]:
percapita = pd.read_excel(url, sheet_name='emissoes_percapita')
percapita.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
fontes = pd.read_excel(url, sheet_name='fontes', usecols=[0,1,2,3])
fontes.head()

          País ISO 3166-1 alpha-3   Ano   Total
0  Afeganistão                AFG  1750  [NONE]
1  Afeganistão                AFG  1751  [NONE]
2  Afeganistão                AFG  1752  [NONE]
3  Afeganistão                AFG  1753  [NONE]
4  Afeganistão                AFG  1754  [NONE]

In [12]:
fontes = pd.read_excel(url, sheet_name='fontes', usecols='A:D')
fontes.head()

          País ISO 3166-1 alpha-3   Ano   Total
0  Afeganistão                AFG  1750  [NONE]
1  Afeganistão                AFG  1751  [NONE]
2  Afeganistão                AFG  1752  [NONE]
3  Afeganistão                AFG  1753  [NONE]
4  Afeganistão                AFG  1754  [NONE]

In [14]:
fontes.to_excel('Fontes_emissões.xlsx', index=False)

In [13]:
#dados relevantes apartir da linha 50
#4 paginas quero ler só pagamento
#colunas relevantes da F:L
#dados = pd.read_xlsx(url, sheet_name='pagamentos', usecols='F:L', nrows=50)