In [43]:
import pandas as pd

In [44]:
nivel_estudantil_idade = {"Escolaridade":["Ensino medio","Graduação","Pós-Graduação","Especialização"],
                          "Idade":[17,25,30,35]}

In [45]:
nivel_estudantil_idade = pd.DataFrame(nivel_estudantil_idade)
nivel_estudantil_idade

     Escolaridade  Idade
0    Ensino medio     17
1       Graduação     25
2   Pós-Graduação     30
3  Especialização     35

In [46]:
selecao1 = nivel_estudantil_idade[nivel_estudantil_idade["Idade"] == 17].sum()
selecao1

Escolaridade    Ensino medio
Idade                     17
dtype: object

In [47]:
nivel_estudantil_idade.loc[len(nivel_estudantil_idade)]={"Escolaridade":"Ensino Medio", "Idade":17}

In [48]:
nivel_estudantil_idade

     Escolaridade  Idade
0    Ensino medio     17
1       Graduação     25
2   Pós-Graduação     30
3  Especialização     35
4    Ensino Medio     17

In [49]:
nivel_estudantil_idade.drop(5, axis=0, inplace=True)

KeyError: '[5] not found in axis'

In [50]:
nivel_estudantil_idade

     Escolaridade  Idade
0    Ensino medio     17
1       Graduação     25
2   Pós-Graduação     30
3  Especialização     35
4    Ensino Medio     17

In [51]:
nivel_estudantil_idade.loc[len(nivel_estudantil_idade)] = {"Escolaridade": "Mestrado", "Idade":35}

In [52]:
nivel_estudantil_idade.drop(4,axis=0, inplace=True)

In [53]:
nivel_estudantil_idade

     Escolaridade  Idade
0    Ensino medio     17
1       Graduação     25
2   Pós-Graduação     30
3  Especialização     35
5        Mestrado     35

In [54]:
selecao2=nivel_estudantil_idade["Idade"]==35
selecao2

0    False
1    False
2    False
3     True
5     True
Name: Idade, dtype: bool

In [55]:
nivel_estudantil_idade.query("Idade==35")

     Escolaridade  Idade
3  Especialização     35
5        Mestrado     35

In [60]:
nivel_estudantil_idade.query('Escolaridade == "Mestrado"')

  Escolaridade  Idade
5     Mestrado     35

In [64]:
nivel_estudantil_idade.query('Escolaridade == "Ensino medio" & Idade==17')

   Escolaridade  Idade
0  Ensino medio     17

In [65]:
nivel_estudantil_idade.loc[len(nivel_estudantil_idade)] = {"Escolaridade":"Ensino medio", "Idade":17}

In [66]:
nivel_estudantil_idade

     Escolaridade  Idade
0    Ensino medio     17
1       Graduação     25
2   Pós-Graduação     30
3  Especialização     35
5    Ensino medio     17

In [68]:
nivel_estudantil_idade.query('Escolaridade=="Ensino medio"')

   Escolaridade  Idade
0  Ensino medio     17
5  Ensino medio     17

In [69]:
nivel_estudantil_idade.loc[len(nivel_estudantil_idade)] = {"Escolaridade":"Ensino medio", "Idade":19}

In [70]:
nivel_estudantil_idade

     Escolaridade  Idade
0    Ensino medio     17
1       Graduação     25
2   Pós-Graduação     30
3  Especialização     35
5    Ensino medio     19

In [71]:
nivel_estudantil_idade.query('Escolaridade=="Ensino medio" & Idade==19')

   Escolaridade  Idade
5  Ensino medio     19