In [18]:
import pandas as pd

dados = pd.DataFrame([['Feira', 'Cebola', 2.5],
                        ['Mercado', 'Cebola', 1.99],
                        ['Supermercado', 'Cebola', 1.69],
                        ['Feira', 'Tomate', 4],
                        ['Mercado', 'Tomate', 3.29],
                        ['Supermercado', 'Tomate', 2.99],
                        ['Feira', 'Batata', 4.2],
                        ['Mercado', 'Batata', 3.99],
                        ['Supermercado', 'Batata', 3.69]],
                        columns = ['Local', 'Produto', 'Preço'])
dados

          Local Produto  Preço
0         Feira  Cebola   2.50
1       Mercado  Cebola   1.99
2  Supermercado  Cebola   1.69
3         Feira  Tomate   4.00
4       Mercado  Tomate   3.29
5  Supermercado  Tomate   2.99
6         Feira  Batata   4.20
7       Mercado  Batata   3.99
8  Supermercado  Batata   3.69

In [19]:

dados[dados["Local"] == "Supermercado"]

          Local Produto  Preço
2  Supermercado  Cebola   1.69
5  Supermercado  Tomate   2.99
8  Supermercado  Batata   3.69

In [20]:
#Remover permanentemente da coluna local o Supermercado

dados[dados["Local"] == "Supermercado"].index

Index([2, 5, 8], dtype='int64')

In [21]:
dados.drop([2,5,8], axis=0, inplace=True)

In [22]:
dados

     Local Produto  Preço
0    Feira  Cebola   2.50
1  Mercado  Cebola   1.99
3    Feira  Tomate   4.00
4  Mercado  Tomate   3.29
6    Feira  Batata   4.20
7  Mercado  Batata   3.99