In [19]:
import pandas as pd

# Exercicio 01
DESAFIO DE HOJE — NÍVEL BASE PROFISSIONAL

Você recebe um DataFrame com vendas:

In [20]:
exercicio_1 = pd.DataFrame({
    "produto": ["A", "B", "A", "C", "B", "A", "C", "C"],
    "categoria": ["tech", "tech", "tech", "casa", "tech", "tech", "casa", "casa"],
    "preco": [100, 200, 100, 300, 200, 100, 300, 300],
    "quantidade": [1, 2, 1, 3, 1, 2, 1, 2],
    "cliente_id": [10, 11, 12, 10, 13, 11, 14, 15]
})

- Vende mais itens para casa ou tech? total
- Essas vendas vendem em mais quantidades para casa ou tech?
- Quais produtos vendem mais?

Você esqueceu a métrica financeira.

Você olhou:

quantidade

produto

categoria

Qual categoria gera mais receita?

Qual produto gera mais receita?

Qual cliente gera mais receita?

Receita por categoria é concentrada ou distribuída?

## Crie a coluna receita.

In [21]:
exercicio_1['Receita'] = exercicio_1['preco'] * exercicio_1['quantidade']
exercicio_1

  produto categoria  preco  quantidade  cliente_id  Receita
0       A      tech    100           1          10      100
1       B      tech    200           2          11      400
2       A      tech    100           1          12      100
3       C      casa    300           3          10      900
4       B      tech    200           1          13      200
5       A      tech    100           2          11      200
6       C      casa    300           1          14      300
7       C      casa    300           2          15      600

## Calcule receita total por categoria e ordene do maior pro menor.

In [22]:
exercicio_1['Receita_total'] = exercicio_1.groupby('categoria')['Receita'].transform('sum')
exercicio_1

  produto categoria  preco  quantidade  cliente_id  Receita  Receita_total
0       A      tech    100           1          10      100           1000
1       B      tech    200           2          11      400           1000
2       A      tech    100           1          12      100           1000
3       C      casa    300           3          10      900           1800
4       B      tech    200           1          13      200           1000
5       A      tech    100           2          11      200           1000
6       C      casa    300           1          14      300           1800
7       C      casa    300           2          15      600           1800

## Calcule quantidade total por categoria.

In [23]:
exercicio_1.groupby('categoria')['quantidade'].sum()

categoria
casa    6
tech    7
Name: quantidade, dtype: int64

## Calcule receita total por produto e pegue o top 2.

In [24]:
receita_total_produtos = exercicio_1.groupby('produto')['Receita_total'].sum().sort_values(ascending=False)
receita_total_produtos[0:2]

produto
C    5400
A    3000
Name: Receita_total, dtype: int64

# Exercicio 02
A HABILIDADE QUE VOCÊ QUER DESENVOLVER

Você quer parar de escrever código “no automático”
e começar a enxergar o que cada método devolve.

In [26]:
exercicio_2 = exercicio_1.copy()
exercicio_2

  produto categoria  preco  quantidade  cliente_id  Receita  Receita_total
0       A      tech    100           1          10      100           1000
1       B      tech    200           2          11      400           1000
2       A      tech    100           1          12      100           1000
3       C      casa    300           3          10      900           1800
4       B      tech    200           1          13      200           1000
5       A      tech    100           2          11      200           1000
6       C      casa    300           1          14      300           1800
7       C      casa    300           2          15      600           1800

## Faça cada linha isoladamente:

Selecione uma coluna.

Veja o tipo dela.

Aplique .sum() nessa coluna.

Veja o tipo.

Aplique .mean() na coluna original (não na soma).

Veja o tipo.

In [31]:
exercicio_2['preco']

0    100
1    200
2    100
3    300
4    200
5    100
6    300
7    300
Name: preco, dtype: int64

Pega coluna inteira - Series, o int64 é em relação aos valores dentro da lista

estrutura = Series
tipo interno dos dados = int64

ou seja não é mais estrutura pandas é um valor, um numero

📦 Series = caixa com vários valores
🔢 int64 = valor único

In [32]:
type(exercicio_2['preco']) #Series

pandas.core.series.Series

com soma ou media, saimos da estrutura e obtemos um unico valor

In [33]:
type(exercicio_2['preco'].sum())#int

numpy.int64

quando somado se torna valor inteiro

In [34]:
type(exercicio_2['preco'].mean())#float

numpy.float64

quando pedido media, existem valores quebrados que o faz se tornar float

1️⃣ groupby("categoria")

Retorna → DataFrameGroupBy

Isso não é DataFrame.
É um objeto intermediário.
Ele ainda não calculou nada.

É como se fosse:
“Eu agrupei, mas ainda não fiz conta.”

In [37]:
type(exercicio_2.groupby('categoria'))

pandas.core.groupby.generic.DataFrameGroupBy

1️⃣ groupby("categoria")

Retorna → DataFrameGroupBy

Isso não é DataFrame.
É um objeto intermediário.
Ele ainda não calculou nada.

É como se fosse:
“Eu agrupei, mas ainda não fiz conta.”

In [38]:
type(exercicio_2.groupby('categoria')['preco'])

pandas.core.groupby.generic.SeriesGroupBy

groupby("categoria")["preco"].sum()

Retorna → Series

Agora sim houve agregação.
Ele somou cada grupo.
Mas não virou número único.
Virou uma Series indexada por categoria.

Por isso você ainda pode fazer:

.sort_values()

.mean()

slicing

.head()

In [39]:
type(exercicio_2.groupby('categoria')['preco'].sum())

pandas.core.series.Series

teste mental
como existem dois colchetes, é sobre  linha não sobre coluna, resultado int

errei, ele não retorna um valor da linha, ainda é estrutura, mas não completa

In [40]:
type(exercicio_2[["preco"]])

pandas.core.frame.DataFrame

Um colchete ["preco"] → pega uma coluna como Series

Dois colchetes [["preco"]] → pega uma lista de colunas
E lista de colunas sempre retorna DataFrame, mesmo que tenha só uma.