In [ ]:
import pandas as pd

In [ ]:
dados = ({
    'Nome':["Peixoto","Cabra-Peste","Junin","Rodolfo","Pitanga"],
    'Sobrenome':["Barroso","Chupisco", "Inverno", "Patati", "Patata"],
    'Idade':[12,13,15,11,17],
    'Altura':[2.20,1.85,1.62,1.55,2.10]
})
dados

{'Nome': ['Peixoto', 'Cabra-Peste', 'Junin', 'Rodolfo', 'Pitanga'],
 'Sobrenome': ['Barroso', 'Chupisco', 'Inverno', 'Patati', 'Patata'],
 'Idade': [12, 13, 15, 11, 17],
 'Altura': [2.2, 1.85, 1.62, 1.55, 2.1]}

In [ ]:
dados = pd.DataFrame(dados)
dados.head()

          Nome Sobrenome  Idade  Altura
0      Peixoto   Barroso     12    2.20
1  Cabra-Peste  Chupisco     13    1.85
2        Junin   Inverno     15    1.62
3      Rodolfo    Patati     11    1.55
4      Pitanga    Patata     17    2.10

In [11]:
dados.nlargest(5,'Altura')

          Nome Sobrenome  Idade  Altura
0      Peixoto   Barroso     12    2.20
4      Pitanga    Patata     17    2.10
1  Cabra-Peste  Chupisco     13    1.85
2        Junin   Inverno     15    1.62
3      Rodolfo    Patati     11    1.55

In [12]:
dados.nlargest(5, "Idade")

          Nome Sobrenome  Idade  Altura
4      Pitanga    Patata     17    2.10
2        Junin   Inverno     15    1.62
1  Cabra-Peste  Chupisco     13    1.85
0      Peixoto   Barroso     12    2.20
3      Rodolfo    Patati     11    1.55

In [14]:
dados.columns

Index(['Nome', 'Sobrenome', 'Idade', 'Altura'], dtype='object')

In [16]:
dados.dtypes

TypeError: 'Series' object is not callable