In [ ]:
import pandas as pd

# Exercicio 01
DESAFIO DE HOJE — NÍVEL BASE PROFISSIONAL

Você recebe um DataFrame com vendas:

In [ ]:
exercicio_1 = pd.DataFrame({
    "produto": ["A", "B", "A", "C", "B", "A", "C", "C"],
    "categoria": ["tech", "tech", "tech", "casa", "tech", "tech", "casa", "casa"],
    "preco": [100, 200, 100, 300, 200, 100, 300, 300],
    "quantidade": [1, 2, 1, 3, 1, 2, 1, 2],
    "cliente_id": [10, 11, 12, 10, 13, 11, 14, 15]
})

- Vende mais itens para casa ou tech? total
- Essas vendas vendem em mais quantidades para casa ou tech?
- Quais produtos vendem mais?

Você esqueceu a métrica financeira.

Você olhou:

quantidade

produto

categoria

Qual categoria gera mais receita?

Qual produto gera mais receita?

Qual cliente gera mais receita?

Receita por categoria é concentrada ou distribuída?

## Crie a coluna receita.

In [ ]:
exercicio_1['Receita'] = exercicio_1['preco'] * exercicio_1['quantidade']
exercicio_1

  produto categoria  preco  quantidade  cliente_id  Receita
0       A      tech    100           1          10      100
1       B      tech    200           2          11      400
2       A      tech    100           1          12      100
3       C      casa    300           3          10      900
4       B      tech    200           1          13      200
5       A      tech    100           2          11      200
6       C      casa    300           1          14      300
7       C      casa    300           2          15      600

## Calcule receita total por categoria e ordene do maior pro menor.

In [ ]:
exercicio_1['Receita_total'] = exercicio_1.groupby('categoria')['Receita'].transform('sum')
exercicio_1

  produto categoria  preco  quantidade  cliente_id  Receita  Receita_total
0       A      tech    100           1          10      100           1000
1       B      tech    200           2          11      400           1000
2       A      tech    100           1          12      100           1000
3       C      casa    300           3          10      900           1800
4       B      tech    200           1          13      200           1000
5       A      tech    100           2          11      200           1000
6       C      casa    300           1          14      300           1800
7       C      casa    300           2          15      600           1800

## Calcule quantidade total por categoria.

In [ ]:
exercicio_1.groupby('categoria')['quantidade'].sum()

categoria
casa    6
tech    7
Name: quantidade, dtype: int64

## Calcule receita total por produto e pegue o top 2.

In [ ]:
receita_total_produtos = exercicio_1.groupby('produto')['Receita_total'].sum().sort_values(ascending=False)
receita_total_produtos[0:2]

produto
C    5400
A    3000
Name: Receita_total, dtype: int64

# Exercicio 02
A HABILIDADE QUE VOCÊ QUER DESENVOLVER

Você quer parar de escrever código “no automático”
e começar a enxergar o que cada método devolve.

In [ ]:
exercicio_2 = exercicio_1.copy()
exercicio_2

  produto categoria  preco  quantidade  cliente_id  Receita  Receita_total
0       A      tech    100           1          10      100           1000
1       B      tech    200           2          11      400           1000
2       A      tech    100           1          12      100           1000
3       C      casa    300           3          10      900           1800
4       B      tech    200           1          13      200           1000
5       A      tech    100           2          11      200           1000
6       C      casa    300           1          14      300           1800
7       C      casa    300           2          15      600           1800

## Faça cada linha isoladamente:

Selecione uma coluna.

Veja o tipo dela.

Aplique .sum() nessa coluna.

Veja o tipo.

Aplique .mean() na coluna original (não na soma).

Veja o tipo.

In [ ]:
exercicio_2['preco']

0    100
1    200
2    100
3    300
4    200
5    100
6    300
7    300
Name: preco, dtype: int64

Pega coluna inteira - Series, o int64 é em relação aos valores dentro da lista

estrutura = Series
tipo interno dos dados = int64

ou seja não é mais estrutura pandas é um valor, um numero

📦 Series = caixa com vários valores
🔢 int64 = valor único

In [ ]:
type(exercicio_2['preco']) #Series

pandas.core.series.Series

com soma ou media, saimos da estrutura e obtemos um unico valor

In [ ]:
type(exercicio_2['preco'].sum())#int

numpy.int64

quando somado se torna valor inteiro

In [ ]:
type(exercicio_2['preco'].mean())#float

numpy.float64

quando pedido media, existem valores quebrados que o faz se tornar float

1️⃣ groupby("categoria")

Retorna → DataFrameGroupBy

Isso não é DataFrame.
É um objeto intermediário.
Ele ainda não calculou nada.

É como se fosse:
“Eu agrupei, mas ainda não fiz conta.”

In [ ]:
type(exercicio_2.groupby('categoria'))

pandas.core.groupby.generic.DataFrameGroupBy

1️⃣ groupby("categoria")

Retorna → DataFrameGroupBy

Isso não é DataFrame.
É um objeto intermediário.
Ele ainda não calculou nada.

É como se fosse:
“Eu agrupei, mas ainda não fiz conta.”

In [ ]:
type(exercicio_2.groupby('categoria')['preco'])

pandas.core.groupby.generic.SeriesGroupBy

groupby("categoria")["preco"].sum()

Retorna → Series

Agora sim houve agregação.
Ele somou cada grupo.
Mas não virou número único.
Virou uma Series indexada por categoria.

Por isso você ainda pode fazer:

.sort_values()

.mean()

slicing

.head()

In [ ]:
type(exercicio_2.groupby('categoria')['preco'].sum())

pandas.core.series.Series

teste mental
como existem dois colchetes, é sobre  linha não sobre coluna, resultado int

errei, ele não retorna um valor da linha, ainda é estrutura, mas não completa

In [ ]:
type(exercicio_2[["preco"]])

pandas.core.frame.DataFrame

Um colchete ["preco"] → pega uma coluna como Series

Dois colchetes [["preco"]] → pega uma lista de colunas
E lista de colunas sempre retorna DataFrame, mesmo que tenha só uma.

# Desafio 1
Você foi contratado por uma consultoria especializada em soluções para o varejo. Sua primeira missão é automatizar o sistema de promoções de uma grande rede de lojas. O sistema deve analisar o valor total da compra de um cliente e, de acordo com regras de negócio, decidir qual benefício será aplicado. Dependendo do valor, o cliente pode ganhar um desconto, um brinde ou apenas uma mensagem de agradecimento. Sua tarefa é implementar a lógica que, a partir do valor da compra, determina e exibe a mensagem correta para cada situação, garantindo que o sistema funcione de forma automática e sem erros.

Implemente um programa que leia o valor total da compra (um número inteiro representando reais) e, usando estruturas condicionais, imprima uma das seguintes mensagens:
- Se o valor for menor que 50, imprima "Obrigado por comprar conosco!"
- Se o valor for de 50 a 99 (inclusive), imprima "Parabens! Voce ganhou um brinde!"
- Se o valor for de 100 a 199 (inclusive), imprima "Desconto de 10 reais aplicado!"
- Se o valor for 200 ou mais, imprima "Desconto de 25 reais aplicado!"

* Entrada
Um único número inteiro representando o valor total da compra em reais. O valor será sempre maior ou igual a zero.

* Saída
Uma única linha contendo a mensagem correspondente ao benefício aplicado, exatamente como especificado nas regras acima.

* Exemplos
A tabela abaixo apresenta exemplos de entrada e saída:

Entrada	Saída
- 30	Obrigado por comprar conosco!
- 75	Parabens! Voce ganhou um brinde!
- 150	Desconto de 10 reais aplicado!
- 250	Desconto de 25 reais aplicado!

In [12]:
valor_compra = int(input())

# TODO: Implemente a estrutura condicional para decidir e imprimir a mensagem correta
# Dica: Use if, elif e else para comparar o valor_compra com as faixas especificadas no enunciado.
if valor_compra<50:
  print('Obrigado por comprar conosco!')#correto
elif valor_compra>=50 and valor_compra<=99:
  print( "Parabens! Voce ganhou um brinde!")#correto
elif valor_compra>=100 and valor_compra<=199:
  print('Desconto de 10 reais aplicado!')
elif valor_compra>=200:
  print('Desconto de 25 reais aplicado!')

200
Desconto de 25 reais aplicado!

# Desafio 2
Você foi contratado por uma consultoria para auxiliar uma empresa do setor financeiro a automatizar a validação de transações bancárias. Cada transação possui um valor e uma taxa de serviço. O sistema precisa calcular o valor final da transação (valor menos taxa) e verificar se o valor final é suficiente para cobrir um pagamento mínimo exigido pela empresa. Caso o valor final seja igual ou superior ao pagamento mínimo, a transação é aprovada; caso contrário, é recusada. Sua tarefa é implementar essa lógica utilizando operadores e expressões em Python, garantindo que o sistema seja confiável e preciso para o negócio.

Implemente um programa que leia três números inteiros: o valor da transação, a taxa de serviço e o pagamento mínimo. Calcule o valor final da transação subtraindo a taxa do valor. Se o valor final for maior ou igual ao pagamento mínimo, imprima "Aprovada". Caso contrário, imprima "Recusada".

* Entrada
Três números inteiros separados por espaço, representando respectivamente o valor da transação, a taxa de serviço e o pagamento mínimo.

* Saída
Uma única palavra: "Aprovada" se o valor final for suficiente, ou "Recusada" caso contrário.

* Exemplos
A tabela abaixo apresenta exemplos de entrada e saída:

Entrada	Saída
- 100 10 80	Aprovada
- 50 20 40	Recusada
- 200 50 150	Aprovada
- 75 30 50	Recusada

In [18]:
# Leitura dos três valores inteiros em uma única linha
entrada = input()
valor_transacao, taxa_servico, pagamento_minimo = map(int, entrada.split())
# TODO: Calcule o valor final da transação subtraindo a taxa do valor
# valor_final = ...
valor_final = valor_transacao - taxa_servico
# Verifique se o valor final é suficiente para aprovar a transação
if valor_final >= pagamento_minimo:
    print("Aprovada")
else:
    print("Recusada")

75 30 50
Recusada

# Desafio 3
Você faz parte da equipe de transformação digital de uma consultoria que está integrando dados de diferentes sistemas legados. Cada sistema armazena nomes de clientes de formas variadas: alguns usam letras maiúsculas, outros minúsculas, e há casos em que nomes vêm com espaços extras no início ou no fim. Para garantir a padronização e facilitar a análise, sua tarefa é criar um programa que normalize esses nomes, removendo espaços desnecessários e ajustando a capitalização de acordo com o padrão: a primeira letra de cada palavra deve ser maiúscula e as demais, minúsculas.

Implemente um programa que receba uma string representando o nome de um cliente, possivelmente com letras em qualquer caixa e espaços extras no início ou no fim. O programa deve retornar o nome formatado corretamente, com apenas um espaço entre as palavras e cada palavra iniciando com letra maiúscula.

* Entrada
Uma única linha contendo uma string representando o nome de um cliente, que pode conter letras maiúsculas ou minúsculas e espaços extras no início ou no fim.

* Saída
Uma única linha contendo o nome do cliente formatado: cada palavra deve começar com letra maiúscula, as demais letras devem ser minúsculas, e deve haver apenas um espaço entre as palavras, sem espaços extras no início ou no fim.

* Exemplos
A tabela abaixo apresenta exemplos de entrada e saída:

Entrada	Saída
- maria da silva	Maria Da Silva
- JOAO PEREIRA	Joao Pereira
- ana costa	Ana Costa
- LuIz feRReira	Luiz Ferreira

In [30]:
# Lê a entrada do usuário (nome do cliente)
entrada = input()

# TODO: Remova espaços extras no início/fim e divida a string em palavras
palavras = entrada.strip()
palavras = entrada.split()
# Dica: Use métodos de string para limpar e separar as palavras
# Capitalize cada palavra (primeira letra maiúscula, demais minúsculas)
palavras_formatadas = [palavra.capitalize() for palavra in palavras]
# Junte as palavras com um único espaço entre elas
nome_formatado = ' '.join(palavras_formatadas)
# Exiba o nome formatado
print(nome_formatado)

ana costa Ana Costa
Ana Costa Ana Costa

* Mesmo resultado com menos linhas e sem capitalize

In [29]:
entrada = input()
palavra = entrada.strip()#remover espaços
palavra = entrada.split()#dividir por palavra
palavra = entrada.title()#adicionar Iniciais maiusculas
print(palavra)#imprimir normalmente

ana costa Ana Costa
Ana Costa Ana Costa